version: '3.8'

services:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db_procorp
        environment:
            PMA_HOST: db_procorp
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - 8080:80
    # KONTEJNER
    db_procorp:
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: procorp
        ports:
            - 3306:3306
        volumes:
            - dbdata:/var/lib/mysql
volumes:
    dbdata:
